[package]
name = "shopp"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "shopp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "*" }
ntex = { version = "*", default-features = false, features = ["async-std"] }
tracing = { version = "*" }
markup = { version = "*" }
uuid = { version = "*", features = ["v4", "fast-rng", "macro-diagnostics", "serde"] }
sqlx = { version = "*", features = ["runtime-async-std", "tls-native-tls", "postgres", "uuid", "chrono", "migrate", "macros"] }

[dev-dependencies]
curl = { version = "*" }