[package]
name = "shopp"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "shopp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "*" }
ntex = { version = "*", features = ["async-std"] }
sqlx = { version = "*", features = ["runtime-async-std", "tls-native-tls"] }
tracing = { version = "*" }