//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use super::sea_orm_active_enums::Mediatype;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "media")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub path: String,
    pub media_type: Mediatype,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::media_to_item::Entity")]
    MediaToItem,
}

impl Related<super::media_to_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaToItem.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
