//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "media_media_set")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub media_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub media_set_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::media::Entity",
        from = "Column::MediaId",
        to = "super::media::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Media,
    #[sea_orm(
        belongs_to = "super::media_set::Entity",
        from = "Column::MediaSetId",
        to = "super::media_set::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MediaSet,
}

impl Related<super::media::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Media.def()
    }
}

impl Related<super::media_set::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaSet.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
