//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod attribute;
pub mod attribute_value;
pub mod category;
pub mod description;
pub mod language;
pub mod media_item;
pub mod media_set;
pub mod product;
pub mod sea_orm_active_enums;
pub mod sku;
pub mod slug;
pub mod variant;
