//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::category::Entity as Category;
pub use super::gallery::Entity as Gallery;
pub use super::language::Entity as Language;
pub use super::media::Entity as Media;
pub use super::product::Entity as Product;
pub use super::sku::Entity as Sku;
pub use super::slug::Entity as Slug;
