//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::category::Entity as Category;
pub use super::product::Entity as Product;
pub use super::product_to_category::Entity as ProductToCategory;
pub use super::slug::Entity as Slug;
