//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::product_to_category::Entity")]
    ProductToCategory,
}

impl Related<super::product_to_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductToCategory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
