//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "entity_type")]
pub enum EntityType {
    #[sea_orm(string_value = "category")]
    Category,
    #[sea_orm(string_value = "product")]
    Product,
    #[sea_orm(string_value = "sku")]
    Sku,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "media_role")]
pub enum MediaRole {
    #[sea_orm(string_value = "description")]
    Description,
    #[sea_orm(string_value = "downloadable")]
    Downloadable,
    #[sea_orm(string_value = "gallery")]
    Gallery,
    #[sea_orm(string_value = "instructions")]
    Instructions,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "media_type")]
pub enum MediaType {
    #[sea_orm(string_value = "audio")]
    Audio,
    #[sea_orm(string_value = "document")]
    Document,
    #[sea_orm(string_value = "image")]
    Image,
    #[sea_orm(string_value = "video")]
    Video,
}
