//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sku")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    #[sea_orm(unique)]
    pub ean: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sku_to_product::Entity")]
    SkuToProduct,
}

impl Related<super::sku_to_product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SkuToProduct.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
